FROM golang:1.25-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY src ./src
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/ramadan-arc ./src/cmd/main.go

FROM alpine:3.20

WORKDIR /app
COPY --from=build /bin/ramadan-arc /bin/ramadan-arc
COPY src/db ./src/db
EXPOSE 8080
CMD ["/bin/ramadan-arc"]
